# Python stubs generated by omniidl from WordyGame.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "WordyGame"
#
__name__ = "WordyGame"
_0_WordyGame = omniORB.openModule("WordyGame", r"WordyGame.idl")
_0_WordyGame__POA = omniORB.openModule("WordyGame__POA", r"WordyGame.idl")


# typedef ... StringSeq
class StringSeq:
    _NP_RepositoryId = "IDL:WordyGame/StringSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_WordyGame.StringSeq = StringSeq
_0_WordyGame._d_StringSeq  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_WordyGame._ad_StringSeq = (omniORB.tcInternal.tv_alias, StringSeq._NP_RepositoryId, "StringSeq", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_WordyGame._tc_StringSeq = omniORB.tcInternal.createTypeCode(_0_WordyGame._ad_StringSeq)
omniORB.registerType(StringSeq._NP_RepositoryId, _0_WordyGame._ad_StringSeq, _0_WordyGame._tc_StringSeq)
del StringSeq

# enum LoginResult
_0_WordyGame.SUCCESS = omniORB.EnumItem("SUCCESS", 0)
_0_WordyGame.INVALID_CREDENTIALS = omniORB.EnumItem("INVALID_CREDENTIALS", 1)
_0_WordyGame.ACCOUNT_ALREADY_LOGGED_IN = omniORB.EnumItem("ACCOUNT_ALREADY_LOGGED_IN", 2)
_0_WordyGame.LoginResult = omniORB.Enum("IDL:WordyGame/LoginResult:1.0", (_0_WordyGame.SUCCESS, _0_WordyGame.INVALID_CREDENTIALS, _0_WordyGame.ACCOUNT_ALREADY_LOGGED_IN,))

_0_WordyGame._d_LoginResult  = (omniORB.tcInternal.tv_enum, _0_WordyGame.LoginResult._NP_RepositoryId, "LoginResult", _0_WordyGame.LoginResult._items)
_0_WordyGame._tc_LoginResult = omniORB.tcInternal.createTypeCode(_0_WordyGame._d_LoginResult)
omniORB.registerType(_0_WordyGame.LoginResult._NP_RepositoryId, _0_WordyGame._d_LoginResult, _0_WordyGame._tc_LoginResult)

# struct WordyGamePlayer
_0_WordyGame.WordyGamePlayer = omniORB.newEmptyClass()
class WordyGamePlayer (omniORB.StructBase):
    _NP_RepositoryId = "IDL:WordyGame/WordyGamePlayer:1.0"

    def __init__(self, username, wins):
        self.username = username
        self.wins = wins

_0_WordyGame.WordyGamePlayer = WordyGamePlayer
_0_WordyGame._d_WordyGamePlayer  = (omniORB.tcInternal.tv_struct, WordyGamePlayer, WordyGamePlayer._NP_RepositoryId, "WordyGamePlayer", "username", (omniORB.tcInternal.tv_string,0), "wins", omniORB.tcInternal.tv_long)
_0_WordyGame._tc_WordyGamePlayer = omniORB.tcInternal.createTypeCode(_0_WordyGame._d_WordyGamePlayer)
omniORB.registerType(WordyGamePlayer._NP_RepositoryId, _0_WordyGame._d_WordyGamePlayer, _0_WordyGame._tc_WordyGamePlayer)
del WordyGamePlayer

# interface WordyGameServer
_0_WordyGame._d_WordyGameServer = (omniORB.tcInternal.tv_objref, "IDL:WordyGame/WordyGameServer:1.0", "WordyGameServer")
omniORB.typeMapping["IDL:WordyGame/WordyGameServer:1.0"] = _0_WordyGame._d_WordyGameServer
_0_WordyGame.WordyGameServer = omniORB.newEmptyClass()
class WordyGameServer :
    _NP_RepositoryId = _0_WordyGame._d_WordyGameServer[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_WordyGame.WordyGameServer = WordyGameServer
_0_WordyGame._tc_WordyGameServer = omniORB.tcInternal.createTypeCode(_0_WordyGame._d_WordyGameServer)
omniORB.registerType(WordyGameServer._NP_RepositoryId, _0_WordyGame._d_WordyGameServer, _0_WordyGame._tc_WordyGameServer)

# WordyGameServer operations and attributes
WordyGameServer._d_login = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.typeMapping["IDL:WordyGame/LoginResult:1.0"], ), None)
WordyGameServer._d_logout = (((omniORB.tcInternal.tv_string,0), ), (), None)
WordyGameServer._d_playGame = (((omniORB.tcInternal.tv_string,0), ), (), None)
WordyGameServer._d_getLongestWords = ((), (omniORB.typeMapping["IDL:WordyGame/StringSeq:1.0"], ), None)
WordyGameServer._d_getTopPlayers = ((), (omniORB.typeMapping["IDL:WordyGame/StringSeq:1.0"], ), None)

# WordyGameServer object reference
class _objref_WordyGameServer (CORBA.Object):
    _NP_RepositoryId = WordyGameServer._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def login(self, *args):
        return self._obj.invoke("login", _0_WordyGame.WordyGameServer._d_login, args)

    def logout(self, *args):
        return self._obj.invoke("logout", _0_WordyGame.WordyGameServer._d_logout, args)

    def playGame(self, *args):
        return self._obj.invoke("playGame", _0_WordyGame.WordyGameServer._d_playGame, args)

    def getLongestWords(self, *args):
        return self._obj.invoke("getLongestWords", _0_WordyGame.WordyGameServer._d_getLongestWords, args)

    def getTopPlayers(self, *args):
        return self._obj.invoke("getTopPlayers", _0_WordyGame.WordyGameServer._d_getTopPlayers, args)

omniORB.registerObjref(WordyGameServer._NP_RepositoryId, _objref_WordyGameServer)
_0_WordyGame._objref_WordyGameServer = _objref_WordyGameServer
del WordyGameServer, _objref_WordyGameServer

# WordyGameServer skeleton
__name__ = "WordyGame__POA"
class WordyGameServer (PortableServer.Servant):
    _NP_RepositoryId = _0_WordyGame.WordyGameServer._NP_RepositoryId


    _omni_op_d = {"login": _0_WordyGame.WordyGameServer._d_login, "logout": _0_WordyGame.WordyGameServer._d_logout, "playGame": _0_WordyGame.WordyGameServer._d_playGame, "getLongestWords": _0_WordyGame.WordyGameServer._d_getLongestWords, "getTopPlayers": _0_WordyGame.WordyGameServer._d_getTopPlayers}

WordyGameServer._omni_skeleton = WordyGameServer
_0_WordyGame__POA.WordyGameServer = WordyGameServer
omniORB.registerSkeleton(WordyGameServer._NP_RepositoryId, WordyGameServer)
del WordyGameServer
__name__ = "WordyGame"

# exception NoPlayersAvailable
_0_WordyGame.NoPlayersAvailable = omniORB.newEmptyClass()
class NoPlayersAvailable (CORBA.UserException):
    _NP_RepositoryId = "IDL:WordyGame/NoPlayersAvailable:1.0"

    def __init__(self, reason):
        CORBA.UserException.__init__(self, reason)
        self.reason = reason

_0_WordyGame.NoPlayersAvailable = NoPlayersAvailable
_0_WordyGame._d_NoPlayersAvailable  = (omniORB.tcInternal.tv_except, NoPlayersAvailable, NoPlayersAvailable._NP_RepositoryId, "NoPlayersAvailable", "reason", (omniORB.tcInternal.tv_string,0))
_0_WordyGame._tc_NoPlayersAvailable = omniORB.tcInternal.createTypeCode(_0_WordyGame._d_NoPlayersAvailable)
omniORB.registerType(NoPlayersAvailable._NP_RepositoryId, _0_WordyGame._d_NoPlayersAvailable, _0_WordyGame._tc_NoPlayersAvailable)
del NoPlayersAvailable

#
# End of module "WordyGame"
#
__name__ = "WordyGame_idl"

_exported_modules = ( "WordyGame", )

# The end.
