# DO NOT EDIT THIS FILE!
#
# Python module WordyGame generated by omniidl

import omniORB
omniORB.updateModule("WordyGame")

# ** 1. Stub files contributing to this module
import WordyGame_idl

# ** 2. Sub-modules

# ** 3. End
